In [1]:
import numpy as np

In [2]:
electricity = np.array([85.5, 62.0, 110.0, 145.0, 98.0])

In [3]:
print("Electricity array:", electricity)

Electricity array: [ 85.5  62.  110.  145.   98. ]

In [4]:
print("Array type:", type(electricity))

Array type: <class 'numpy.ndarray'>

In [5]:
print("Dimensions:", electricity.ndim)

Dimensions: 1

In [6]:
print("Shape:", electricity.shape)

Shape: (5,)

In [7]:
print("Number of elements:", electricity.size)

Number of elements: 5

In [8]:
print("Data type:", electricity.dtype)

Data type: float64

In [9]:
print("Addition:", electricity + 10)

Addition: [ 95.5  72.  120.  155.  108. ]

In [10]:
print("Subtraction:", electricity - 10)

Subtraction: [ 75.5  52.  100.  135.   88. ]

In [11]:
print("Multiplication:", electricity * 2)

Multiplication: [171. 124. 220. 290. 196.]

In [12]:
print("Division:", electricity / 2)

Division: [42.75 31.   55.   72.5  49.  ]

In [13]:
print("Square:", electricity ** 2)

Square: [ 7310.25  3844.   12100.   21025.    9604.  ]

In [14]:
print("Minimum:", np.min(electricity))

Minimum: 62.0

In [15]:
print("Maximum:", np.max(electricity))

Maximum: 145.0

In [16]:
print("Mean:", np.mean(electricity))

Mean: 100.1

In [17]:
print("Median:", np.median(electricity))

Median: 98.0

In [18]:
print("Sum:", np.sum(electricity))

Sum: 500.5

In [19]:
print("Standard deviation:", np.std(electricity))
print("Variance:", np.var(electricity))
print("25th percentile:", np.percentile(electricity, 25))
print("75th percentile:", np.percentile(electricity, 75))

Standard deviation: 27.507089995126712
Variance: 756.64
25th percentile: 85.5
75th percentile: 110.0

In [20]:
high_consumption = electricity[electricity > 100]

print("High consumption:", high_consumption)
print("Count:", len(high_consumption))

High consumption: [110. 145.]
Count: 2

In [21]:
solar = np.array([20.0, 18.0, 35.0, 42.0, 15.0])

In [22]:
net_electricity = electricity - solar

In [23]:
print("Solar energy:", solar)
print("Net electricity:", net_electricity)
print("Total net electricity:", np.sum(net_electricity))

Solar energy: [20. 18. 35. 42. 15.]
Net electricity: [ 65.5  44.   75.  103.   83. ]
Total net electricity: 370.5

In [24]:
import pandas as pd
import numpy as np

df = pd.read_csv("campus_sustainability.csv")

print(df)

   Building_ID  Building_Type  Occupancy  Electricity_kWh  Water_Usage_Liters  \
0         B101      Classroom        120             85.5                1800
1         B102        Library         90             62.0                1200
2         B103   Computer Lab         45            110.0                 900
3         B104         Hostel        210            145.0                5200
4         B105      Cafeteria         75             98.0                3100
5         B106      Classroom        105             78.0                1600
6         B107   Research Lab         32            132.0                 750
7         B108        Library        110             70.5                1350
8         B109         Hostel        185            138.0                4800
9         B110  Sports Center         60             92.0                2200
10        B111      Classroom         95             73.0                1500
11        B112   Computer Lab         50            118.0                 980
12        B113      Cafeteria         80            102.0                3300
13        B114   Research Lab         28            125.0                 700
14        B115  Sports Center         65             88.0                2100

    Solar_Energy_kWh  Temperature_C
0               20.0           29.5
1               18.0           27.0
2               35.0           26.5
3               42.0           30.0
4               15.0           31.5
5               22.0           28.5
6               48.0           25.5
7               25.0           27.5
8               40.0           30.5
9               28.0           32.0
10              19.0           29.0
11              38.0           26.0
12              17.0           31.0
13              45.0           25.0
14              30.0           32.5

In [25]:
df

,Building_ID,Building_Type,Occupancy,Electricity_kWh,Water_Usage_Liters,Solar_Energy_kWh,Temperature_C
0,B101,Classroom,120,85.5,1800,20.0,29.5
1,B102,Library,90,62.0,1200,18.0,27.0
2,B103,Computer Lab,45,110.0,900,35.0,26.5
3,B104,Hostel,210,145.0,5200,42.0,30.0
4,B105,Cafeteria,75,98.0,3100,15.0,31.5
5,B106,Classroom,105,78.0,1600,22.0,28.5
6,B107,Research Lab,32,132.0,750,48.0,25.5
7,B108,Library,110,70.5,1350,25.0,27.5
8,B109,Hostel,185,138.0,4800,40.0,30.5
9,B110,Sports Center,60,92.0,2200,28.0,32.0
10,B111,Classroom,95,73.0,1500,19.0,29.0
11,B112,Computer Lab,50,118.0,980,38.0,26.0
12,B113,Cafeteria,80,102.0,3300,17.0,31.0
13,B114,Research Lab,28,125.0,700,45.0,25.0
14,B115,Sports Center,65,88.0,2100,30.0,32.5

In [26]:
df.head()

,Building_ID,Building_Type,Occupancy,Electricity_kWh,Water_Usage_Liters,Solar_Energy_kWh,Temperature_C
0,B101,Classroom,120,85.5,1800,20.0,29.5
1,B102,Library,90,62.0,1200,18.0,27.0
2,B103,Computer Lab,45,110.0,900,35.0,26.5
3,B104,Hostel,210,145.0,5200,42.0,30.0
4,B105,Cafeteria,75,98.0,3100,15.0,31.5

In [27]:
df.head(3)

,Building_ID,Building_Type,Occupancy,Electricity_kWh,Water_Usage_Liters,Solar_Energy_kWh,Temperature_C
0,B101,Classroom,120,85.5,1800,20.0,29.5
1,B102,Library,90,62.0,1200,18.0,27.0
2,B103,Computer Lab,45,110.0,900,35.0,26.5

In [28]:
df.tail()

,Building_ID,Building_Type,Occupancy,Electricity_kWh,Water_Usage_Liters,Solar_Energy_kWh,Temperature_C
10,B111,Classroom,95,73.0,1500,19.0,29.0
11,B112,Computer Lab,50,118.0,980,38.0,26.0
12,B113,Cafeteria,80,102.0,3300,17.0,31.0
13,B114,Research Lab,28,125.0,700,45.0,25.0
14,B115,Sports Center,65,88.0,2100,30.0,32.5

In [29]:
print("Shape:", df.shape)
print("No. of Rows:", df.shape[0])
print("No. of Columns:", df.shape[1])

Shape: (15, 7)
No. of Rows: 15
No. of Columns: 7

In [30]:
df.columns

Index(['Building_ID', 'Building_Type', 'Occupancy', 'Electricity_kWh',
       'Water_Usage_Liters', 'Solar_Energy_kWh', 'Temperature_C'],
      dtype='object')

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Building_ID         15 non-null     object
 1   Building_Type       15 non-null     object
 2   Occupancy           15 non-null     int64
 3   Electricity_kWh     15 non-null     float64
 4   Water_Usage_Liters  15 non-null     int64
 5   Solar_Energy_kWh    15 non-null     float64
 6   Temperature_C       15 non-null     float64
dtypes: float64(3), int64(2), object(2)
memory usage: 968.0+ bytes

In [32]:
df.describe()

,Occupancy,Electricity_kWh,Water_Usage_Liters,Solar_Energy_kWh,Temperature_C
count,15.000000,15.000000,15.000000,15.000000,15.000000
mean,90.000000,101.133333,2098.666667,29.466667,28.800000
std,51.863833,26.016799,1411.670068,11.115412,2.455315
min,28.000000,62.000000,700.000000,15.000000,25.000000
25%,55.000000,81.750000,1090.000000,19.500000,26.750000
50%,80.000000,98.000000,1600.000000,28.000000,29.000000
75%,107.500000,121.500000,2650.000000,39.000000,30.750000
max,210.000000,145.000000,5200.000000,48.000000,32.500000

In [34]:
df.isnull()

,Building_ID,Building_Type,Occupancy,Electricity_kWh,Water_Usage_Liters,Solar_Energy_kWh,Temperature_C
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False

In [35]:
print("\nMissing values per column:")
df.isnull().sum()

Missing values per column:

Building_ID           0
Building_Type         0
Occupancy             0
Electricity_kWh       0
Water_Usage_Liters    0
Solar_Energy_kWh      0
Temperature_C         0
dtype: int64

In [36]:
print("\nTotal missing values:")
df.isnull().sum().sum()

Total missing values:

np.int64(0)

In [39]:
print("Duplicate rows:")
print(df.duplicated())

print()
print("Total duplicate rows:", df.duplicated().sum())

Duplicate rows:
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

Total duplicate rows: 0

In [41]:
df["Energy_Per_Person"] = df["Electricity_kWh"] / df["Occupancy"]

In [42]:
df

,Building_ID,Building_Type,Occupancy,Electricity_kWh,Water_Usage_Liters,Solar_Energy_kWh,Temperature_C,Energy_Per_Person
0,B101,Classroom,120,85.5,1800,20.0,29.5,0.712500
1,B102,Library,90,62.0,1200,18.0,27.0,0.688889
2,B103,Computer Lab,45,110.0,900,35.0,26.5,2.444444
3,B104,Hostel,210,145.0,5200,42.0,30.0,0.690476
4,B105,Cafeteria,75,98.0,3100,15.0,31.5,1.306667
5,B106,Classroom,105,78.0,1600,22.0,28.5,0.742857
6,B107,Research Lab,32,132.0,750,48.0,25.5,4.125000
7,B108,Library,110,70.5,1350,25.0,27.5,0.640909
8,B109,Hostel,185,138.0,4800,40.0,30.5,0.745946
9,B110,Sports Center,60,92.0,2200,28.0,32.0,1.533333
10,B111,Classroom,95,73.0,1500,19.0,29.0,0.768421
11,B112,Computer Lab,50,118.0,980,38.0,26.0,2.360000
12,B113,Cafeteria,80,102.0,3300,17.0,31.0,1.275000
13,B114,Research Lab,28,125.0,700,45.0,25.0,4.464286
14,B115,Sports Center,65,88.0,2100,30.0,32.5,1.353846

In [43]:
df[["Building_ID", "Occupancy","Electricity_kWh", "Energy_Per_Person"]]

   Building_ID  Occupancy  Electricity_kWh  Energy_Per_Person
0         B101        120             85.5           0.712500
1         B102         90             62.0           0.688889
2         B103         45            110.0           2.444444
3         B104        210            145.0           0.690476
4         B105         75             98.0           1.306667
5         B106        105             78.0           0.742857
6         B107         32            132.0           4.125000
7         B108        110             70.5           0.640909
8         B109        185            138.0           0.745946
9         B110         60             92.0           1.533333
10        B111         95             73.0           0.768421
11        B112         50            118.0           2.360000
12        B113         80            102.0           1.275000
13        B114         28            125.0           4.464286
14        B115         65             88.0           1.353846

In [44]:
df["Net_Electricity_kWh"] = df["Electricity_kWh"] - df["Solar_Energy_kWh"]

In [45]:
df

,Building_ID,Building_Type,Occupancy,Electricity_kWh,Water_Usage_Liters,Solar_Energy_kWh,Temperature_C,Energy_Per_Person,Net_Electricity_kWh
0,B101,Classroom,120,85.5,1800,20.0,29.5,0.712500,65.5
1,B102,Library,90,62.0,1200,18.0,27.0,0.688889,44.0
2,B103,Computer Lab,45,110.0,900,35.0,26.5,2.444444,75.0
3,B104,Hostel,210,145.0,5200,42.0,30.0,0.690476,103.0
4,B105,Cafeteria,75,98.0,3100,15.0,31.5,1.306667,83.0
5,B106,Classroom,105,78.0,1600,22.0,28.5,0.742857,56.0
6,B107,Research Lab,32,132.0,750,48.0,25.5,4.125000,84.0
7,B108,Library,110,70.5,1350,25.0,27.5,0.640909,45.5
8,B109,Hostel,185,138.0,4800,40.0,30.5,0.745946,98.0
9,B110,Sports Center,60,92.0,2200,28.0,32.0,1.533333,64.0
10,B111,Classroom,95,73.0,1500,19.0,29.0,0.768421,54.0
11,B112,Computer Lab,50,118.0,980,38.0,26.0,2.360000,80.0
12,B113,Cafeteria,80,102.0,3300,17.0,31.0,1.275000,85.0
13,B114,Research Lab,28,125.0,700,45.0,25.0,4.464286,80.0
14,B115,Sports Center,65,88.0,2100,30.0,32.5,1.353846,58.0

In [46]:
net = df["Net_Electricity_kWh"]

print("Mean:", net.mean())
print("Median:", net.median())
print("Standard deviation:", net.std())
print("Minimum:", net.min())
print("Maximum:", net.max())
print("Total:", net.sum())
print("Variance:", net.var())
print("Count:", net.count())

Mean: 71.66666666666667
Median: 75.0
Standard deviation: 18.0768860571673
Minimum: 44.0
Maximum: 103.0
Total: 1075.0
Variance: 326.7738095238096
Count: 15

In [47]:
print(df["Net_Electricity_kWh"].std(ddof=0))

17.46393108349002

In [48]:
df["Energy_Category"] = pd.cut(
    df["Electricity_kWh"],
    bins=[-np.inf, 80, 110, np.inf],
    labels=["Low", "Medium", "High"]
)

df[["Building_ID", "Electricity_kWh",
          "Energy_Category"]]

   Building_ID  Electricity_kWh Energy_Category
0         B101             85.5          Medium
1         B102             62.0             Low
2         B103            110.0          Medium
3         B104            145.0            High
4         B105             98.0          Medium
5         B106             78.0             Low
6         B107            132.0            High
7         B108             70.5             Low
8         B109            138.0            High
9         B110             92.0          Medium
10        B111             73.0             Low
11        B112            118.0            High
12        B113            102.0          Medium
13        B114            125.0            High
14        B115             88.0          Medium

In [50]:
high_energy = df[df["Electricity_kWh"] > 100]

high_energy

,Building_ID,Building_Type,Occupancy,Electricity_kWh,Water_Usage_Liters,Solar_Energy_kWh,Temperature_C,Energy_Per_Person,Net_Electricity_kWh,Energy_Category
2,B103,Computer Lab,45,110.0,900,35.0,26.5,2.444444,75.0,Medium
3,B104,Hostel,210,145.0,5200,42.0,30.0,0.690476,103.0,High
6,B107,Research Lab,32,132.0,750,48.0,25.5,4.125000,84.0,High
8,B109,Hostel,185,138.0,4800,40.0,30.5,0.745946,98.0,High
11,B112,Computer Lab,50,118.0,980,38.0,26.0,2.360000,80.0,High
12,B113,Cafeteria,80,102.0,3300,17.0,31.0,1.275000,85.0,Medium
13,B114,Research Lab,28,125.0,700,45.0,25.0,4.464286,80.0,High

In [51]:
high_occupancy = df[df["Occupancy"] > 100]

high_occupancy

,Building_ID,Building_Type,Occupancy,Electricity_kWh,Water_Usage_Liters,Solar_Energy_kWh,Temperature_C,Energy_Per_Person,Net_Electricity_kWh,Energy_Category
0,B101,Classroom,120,85.5,1800,20.0,29.5,0.712500,65.5,Medium
3,B104,Hostel,210,145.0,5200,42.0,30.0,0.690476,103.0,High
5,B106,Classroom,105,78.0,1600,22.0,28.5,0.742857,56.0,Low
7,B108,Library,110,70.5,1350,25.0,27.5,0.640909,45.5,Low
8,B109,Hostel,185,138.0,4800,40.0,30.5,0.745946,98.0,High

In [52]:
labs = df[df["Building_Type"] == "Computer Lab"]

labs

,Building_ID,Building_Type,Occupancy,Electricity_kWh,Water_Usage_Liters,Solar_Energy_kWh,Temperature_C,Energy_Per_Person,Net_Electricity_kWh,Energy_Category
2,B103,Computer Lab,45,110.0,900,35.0,26.5,2.444444,75.0,Medium
11,B112,Computer Lab,50,118.0,980,38.0,26.0,2.360000,80.0,High

In [53]:
result = df[
    (df["Electricity_kWh"] > 100) &
    (df["Solar_Energy_kWh"] > 30)
]

result

,Building_ID,Building_Type,Occupancy,Electricity_kWh,Water_Usage_Liters,Solar_Energy_kWh,Temperature_C,Energy_Per_Person,Net_Electricity_kWh,Energy_Category
2,B103,Computer Lab,45,110.0,900,35.0,26.5,2.444444,75.0,Medium
3,B104,Hostel,210,145.0,5200,42.0,30.0,0.690476,103.0,High
6,B107,Research Lab,32,132.0,750,48.0,25.5,4.125000,84.0,High
8,B109,Hostel,185,138.0,4800,40.0,30.5,0.745946,98.0,High
11,B112,Computer Lab,50,118.0,980,38.0,26.0,2.360000,80.0,High
13,B114,Research Lab,28,125.0,700,45.0,25.0,4.464286,80.0,High

In [54]:
summary = df.groupby("Building_Type", observed=True).agg(
    Average_Electricity=("Electricity_kWh", "mean"),
    Total_Electricity=("Electricity_kWh", "sum"),
    Average_Occupancy=("Occupancy", "mean"),
    Building_Count=("Building_ID", "count")
)

summary

,Average_Electricity,Total_Electricity,Average_Occupancy,Building_Count
Building_Type,,,,
Cafeteria,100.000000,200.0,77.500000,2
Classroom,78.833333,236.5,106.666667,3
Computer Lab,114.000000,228.0,47.500000,2
Hostel,141.500000,283.0,197.500000,2
Library,66.250000,132.5,100.000000,2
Research Lab,128.500000,257.0,30.000000,2
Sports Center,90.000000,180.0,62.500000,2

In [55]:
df_sorted = df.sort_values(
    by="Electricity_kWh",
    ascending=False
)

df_sorted

,Building_ID,Building_Type,Occupancy,Electricity_kWh,Water_Usage_Liters,Solar_Energy_kWh,Temperature_C,Energy_Per_Person,Net_Electricity_kWh,Energy_Category
3,B104,Hostel,210,145.0,5200,42.0,30.0,0.690476,103.0,High
8,B109,Hostel,185,138.0,4800,40.0,30.5,0.745946,98.0,High
6,B107,Research Lab,32,132.0,750,48.0,25.5,4.125000,84.0,High
13,B114,Research Lab,28,125.0,700,45.0,25.0,4.464286,80.0,High
11,B112,Computer Lab,50,118.0,980,38.0,26.0,2.360000,80.0,High
2,B103,Computer Lab,45,110.0,900,35.0,26.5,2.444444,75.0,Medium
12,B113,Cafeteria,80,102.0,3300,17.0,31.0,1.275000,85.0,Medium
4,B105,Cafeteria,75,98.0,3100,15.0,31.5,1.306667,83.0,Medium
9,B110,Sports Center,60,92.0,2200,28.0,32.0,1.533333,64.0,Medium
14,B115,Sports Center,65,88.0,2100,30.0,32.5,1.353846,58.0,Medium
0,B101,Classroom,120,85.5,1800,20.0,29.5,0.712500,65.5,Medium
5,B106,Classroom,105,78.0,1600,22.0,28.5,0.742857,56.0,Low
10,B111,Classroom,95,73.0,1500,19.0,29.0,0.768421,54.0,Low
7,B108,Library,110,70.5,1350,25.0,27.5,0.640909,45.5,Low
1,B102,Library,90,62.0,1200,18.0,27.0,0.688889,44.0,Low

In [ ]:
df.to_csv("campus_sustainability_analyzed.csv", index=False)

print("Analyzed dataset saved successfully!")